import type { Metadata } from "next";
// import "./globals.css";
import NavBar from '@/app/components/NavBar'
// import Footer from '@/app/components/Footer'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div>
        <NavBar/>
        <div className="mt-16"></div>
        {children}
      </div>
  );
}
